server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chinese_poetry?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    database: mysql
  #    #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
  #    hibernate.ddl-auto: update
  #    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  #    database-platform: org.hibernate.dialect.MySQL5Dialect
  hikari:
    pool-name: user-1
    minimum-idle: 30
    maximum-pool-size: 30
    connectionTimeout: 60000
    idleTimeout: 60000
    validationTimeout: 3000
    maxLifetime: 60000
    register-mbeans: true